config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes

  authenticated :user do
    root 'notes#index', as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  def index
    @notes = Note.where(user_id: current_user)
  end

  def show
  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private

  def find_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :content)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NotePad</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=  render 'partials/nav' %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="Container">
<%= yield %>
</div>

</body>
</html>

app/views/notes/_form.html.erb
<div class="container">
  <%= form_for @note do |f| %>
  <div class="form-inputs">
    <div class="form-group">
        <p> Title:   <%= f.text_field :title %> </p>
    </div>

    <div class="form-group">
        <p> Content: <%= f.text_area :content %> </p>
    </div>

    <div class="form-group">
        <%= f.button :CreateNote, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
<h1>Edit Your Note:</h1>
<%= form_for @note do |f| %>
  <p> Title:   <%= f.text_field :title %> </p>
  <p> Content: <%= f.text_area :content %> </p>
               <%= f.button :UpdateNote %>
  <% end %>
<%= link_to "Cancel", note_path %>
</div>
</div>
</div>

app/views/notes/index.html.erb
<div class="container">
  <div class="row">
<% @notes.each do |note| %>
<div class="wrapper_with_padding">
<h2><%= link_to note.title, note %></h2>
<p><%= time_ago_in_words(note.created_at) %></p>
<% end %>
</div>

<h4><%= link_to "New Note", new_note_path %></h2>
</div>
</div>

app/views/notes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
<h1>Add a New Note:</h1>
<%= render 'form'  %>
</div>
</div>
</div>

app/views/notes/show.html.erb
<div class="container">
  <div class="row">
<div class="title">
<h1><%= @note.title %></h1>
</div>

<div class="content">
<p><%= @note.content %></p>
<div>

<p><%= link_to "All Notes", notes_path %></p>
<p><%= link_to "Edit", edit_note_path(@note) %></p>
<%= link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?"} %>
</div>
</div>

app/views/partials/_nav.html.erb
<nav class="navbar-default">
  <% if user_signed_in? %>
  <p class="nav_buttons"><%= link_to "New Note", new_note_path %></p>
  <p class="nav_buttons"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></p>
  <% else %>
  <p class="nav_buttons"><%= link_to "Log In", new_user_session_path %></p>
  <% end %>
  <div class="container-fluid">
    <div class="navbar-header">
      <%= image_tag "4.png", alt:"NotePad", class:"image" %>
      <a class="navbar-brand" href="/">
      </a>
    </div>
  </div>
</nav>
<nav>

app/views/welcome/index.html.erb
<div id="banner">
  <div class="banner_content">
    <h1>Online NotePad</h1>
    <p>Keep Your Thoughts Together</p>
    <button><%= link_to "Sign Up", new_user_registration_path %></button>
  </div>
</div>

<div id="quote">
  <p>"The Internet is just a world passing around notes in a classroom."</p>
  <p>- by Jon Stewart</p>
</div>

<div id="callouts">
<div class="callout_inner">
<div class="callout">
  <h2>Notes</h2>
  <p>ll the blinking in one day equates to having your eyes closed for 30 minutes.</p>
</div>
</div>

<div class="callout_inner">
<div class="callout">
  <h2>Notes</h2>
  <p>ll the blinking in one day equates to having your eyes closed for 30 minutes.</p>
</div>
</div>

<div class="callout_inner">
<div class="callout">
  <h2>Notes</h2>
  <p>ll the blinking in one day equates to having your eyes closed for 30 minutes.</p>
</div>
</div>

</div>